name: Bug Report
description: File a bug report
labels: ["bug"]
assignees:
  - alphapapa
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    attributes:
      label: OS/platform
      description: What operating system or platform are you running Emacs on?
      id: os-platform
    validations:
      required: true
  - type: textarea
    attributes:
      label: Emacs version and provenance
      description: What version of Emacs are you using, where did you acquire it, and how did you install it?
      id: emacs-provenance
    validations:
      required: true
  - type: input
    attributes:
      label: Emacs command
      description: By what method did you run Emacs?  (i.e. what command did you run?)
      id: emacs-command
    validations:
      required: true
  - type: input
    attributes:
      label: Emacs frame type
      description: Did the problem happen on a GUI or tty Emacs frame?
      id: emacs-frame
    validations:
      required: true
  - type: textarea
    id: actions
    attributes:
      label: Actions taken
      description: What actions did you take, step-by-step, in order, before the problem was noticed?
    validations:
      required: true
  - type: textarea
    id: results
    attributes:
      label: Results
      description: What behavior did you observe that seemed wrong?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected results
      description: What behavior did you expect to observe?
    validations:
      required: true
  - type: textarea
    id: backtrace
    attributes:
      label: Backtrace
      description: If an error was signaled, please use `M-x toggle-debug-on-error RET` and cause the error to happen again, then paste the contents of the `*Backtrace*` buffer here.
      render: elisp
  - type: textarea
    id: etc
    attributes:
      label: Etc.
      description: Any other information that seems relevant

